### ISSUE TITLE
Add contactimport.html to templates directory

### ISSUE THREAD

**Issue by progsmile** [roundcube/larry#5]
Hello! From next Roundcube logic, `importcontacts.html` is deprecated
https://github.com/roundcube/roundcubemail/blob/release-1.6/program/actions/contacts/import.php#L276-L282

I would like to have actual `contactimport.html` and if it is matter of file renaming I may create pull request.
Thanks!

**Comment by alecpl** [comment]
What is the issue actually?

**Comment by alecpl** [comment]
Oh, sorry, I didn't notice this ticket is for larry. Yeah, it's just a file rename.

**Comment by progsmile** [comment]
#6 Here it is
